### User Register

POST http://localhost:3000/user
Content-Type: application/json

{
    "email":"ashik1996@gmail.com",
    "phone":"01943723874",
    "firstName":"ashik",
    "lastName":"shuvo",
    "password":"password"
}

### get all user

GET http://localhost:3000/user
Content-Type: application/json