### User Register

POST http://localhost:3000/user
Content-Type: application/json

{
    "email":"ashik1999@outlook.com",
    "phone":"01943723874",
    "firstName":"ashik ahmmed",
    "lastName":"shuvo",
    "password":"password_123"
}

### get all user

GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer {{token}}


### signIn
Post http://localhost:3000/user/local/signIn
Content-Type: application/json

{
    "email":"ashik1999@outlook.com",
    "password":"password_123"
}